apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cert-man-deliverable-role
rules:
- apiGroups: [
    "cert-manager.io"
    ]
  resources: ["*"]
  verbs: ["*"]
---
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-package-and-pkgi-install-role
rules:
  - apiGroups: ["data.packaging.carvel.dev"]
    resources: ["packages"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
  - apiGroups: ["packaging.carvel.dev"]
    resources: ["packageinstalls"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cert-manager-ns-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cert-man-deliverable-role
subjects:
- kind: ServiceAccount
  name: default


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: carvel-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-package-and-pkgi-install-role
subjects:
- kind: ServiceAccount
  name: default